services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: ${CONTAINER_NAME:-open-webui}
    ports:
      - ${PORT:-8080}:8080
    volumes:
      - ${DATA_PATH:-$PWD}/data:/app/backend/data
    restart: unless-stopped
    networks:
      - web_net
networks:
  web_net:
    external: true