global:
  scrape_interval: 5s

scrape_configs:
  - job_name: mysqlexporter
    static_configs:
    - targets:
      - monitor_mysqlexporter:9104
  # - job_name: redisexporter
  #   scrape_interval: 5s
  #   static_configs:
  #   - targets:
  #     - monitor_redisexporter:9121