version: '3.1'

services:
  pgdb:
    image: postgres
    container_name: ${CONTAINER_NAME:-postgredb}
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${PASSWORD}
    volumes:
      - ${PGDATA:-$PWD}/data:/var/lib/postgresql/data
    ports:
      - 5432:${PGPORT:-5432}
    
  # pgadminer:
  #   image: adminer
  #   restart: unless-stopped
  #   ports:
  #     - 8080:${PG_ADMIN_PORT:-8584}

networks:
  web_net:
    external: true