version: '3'

networks:
  rustdesk-net:
    external: false
    # driver: host

services:
  hbbs:
    container_name: ${CONTAINER_NAME}_hbbs
    ports:
      - 21115:21115
      - 21116:21116
      - 21116:21116/udp
      - 21118:21118
    image: rustdesk/rustdesk-server:latest
    command: hbbs -r ${HOST_NAME}:21117 -k ${CLIENT_KEY}
    volumes:
      - ${DATA_PATH}/data:/root
    networks:
      - rustdesk-net
    depends_on:
      - hbbr
    restart: unless-stopped

  hbbr:
    container_name: ${CONTAINER_NAME}_hbbr
    ports:
      - 21117:21117
      - 21119:21119
    image: rustdesk/rustdesk-server:latest
    command: hbbr -k ${CLIENT_KEY}
    volumes:
      - ${DATA_PATH}/data:/root
    networks:
      - rustdesk-net
    restart: unless-stopped
