version: '3'

services:
  mysql8:
    image: mysql
    container_name: ${CONTAINER_NAME:-mysql8}
    command:
    # MySQL8的密码验证方式默认是 caching_sha2_password，但是很多的连接工具还不支持该方式
    # 就需要手动设置下mysql的密码认证方式为以前的 mysql_native_password 方式
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
    # docker的重启策略：在容器退出时总是重启容器，但是不考虑在Docker守护进程启动时就已经停止了的容器
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${PASSWORD}
      TZ: Asia/Shanghai
    ports:
      - 3306:3306
    volumes:
      - ${DATA_PATH:-$PWD}/data:/var/lib/mysql
      - ${DATA_PATH:-$PWD}/conf:/etc/mysql/conf.d
      - ${DATA_PATH:-$PWD}/logs:/logs
    networks:
      - web_net
networks:
  web_net:
    external: true