version: '3'

services:
  mysql8:
    image: mysql:8
    container_name: ${CONTAINER_NAME:-mysql8}
    command:
      # --skip-grant-tables
      # --skip-networking
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
    # docker的重启策略：在容器退出时总是重启容器，但是不考虑在Docker守护进程启动时就已经停止了的容器
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${PASSWORD}
      TZ: Asia/Shanghai
    ports:
      - ${PORT:-3306}:3306
    volumes:
      - ${DATA_PATH:-$PWD}/data:/var/lib/mysql
      - ${DATA_PATH:-$PWD}/conf:/etc/mysql/conf.d
      - ${DATA_PATH:-$PWD}/logs:/logs
    networks:
      - web_net
networks:
  web_net:
    external: true