services:
  pgdb:
    build:
      context: ./build
      dockerfile: Dockerfile
    container_name: ${CONTAINER_NAME:-postgres}
    shm_size: 128mb
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      PGDATA: /var/lib/postgresql/data
      # POSTGRES_INITDB_ARGS:
    volumes:
      - ${DATA_PATH:-$PWD}:/var/lib/postgresql/data
    ports:
      - ${PGPORT:-5432}:5432
networks:
  web_net:
    external: true