version: '3.9'

services:
  pgdb:
    image: postgres
    container_name: ${CONTAINER_NAME:-postgresdb}
    shm_size: 128mb
    restart: always
    environment:
      POSTGRES_PASSWORD: ${PASSWORD}
    volumes:
      - ${PGDATA:-$PWD}/data:/var/lib/postgresql/data
    ports:
      - ${PGPORT:-5432}:5432
    
  pgadminer:
    image: adminer
    restart: unless-stopped
    ports:
      - ${PG_ADMIN_PORT:-8584}:8080

networks:
  web_net:
    external: true