version: '3'

services:
  redis:
    image: redis
    container_name: ${CONTAINER_NAME:-reids_latest}
    # docker的重启策略：在容器退出时总是重启容器，但是不考虑在Docker守护进程启动时就已经停止了的容器
    command:
      - "redis-server"
      - "/usr/local/etc/redis/redis.conf" 
    ports:
      - 6379:6379
    volumes:
      - ${DATA_PATH:-$PWD}/data:/data
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    restart: unless-stopped
    networks:
      - web_net
networks:
  web_net:
    external: true